# -*- coding: utf-8 -*-
"""SummarizeSense — AI Text & Document Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jC1tJUKlsgb2BFYrr0n4eqP7_GW3jWGT
"""

from transformers import T5ForConditionalGeneration, T5Tokenizer

# Load pre-trained model
model_name = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

def summarize(text, max_len=120):
    input_text = "summarize: " + text
    inputs = tokenizer.encode(input_text, return_tensors="pt", max_length=512, truncation=True)
    summary_ids = model.generate(inputs, max_length=max_len, min_length=40, length_penalty=2.0, num_beams=4)
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

# Demo
while True:
    text = input("\nEnter text to summarize (or 'q' to quit): ")
    if text.lower() == "q":
        break
    print("\n📝 Summary:\n", summarize(text))